conf/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from .views import * # for Home view & template


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home, name='home'),
    path('sad/', sad, name='sad'),
    
    path('accounts/', include('users.urls')),        #USERS
    path('workspace/', include('workspaces.urls')),  #WORKSPACE
    path('workspace/id/', include('tasks.urls')),    #TASKS
    
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import *


app_name = 'tasks'
urlpatterns = [
    path('<int:id>/all/', all_tasks, name='all'),
    path('<int:id>/done/', done_tasks, name='done'),
    path('<int:id>/pending/', pending_tasks, name='pending'),
    path('<int:id>/mytasks/', own_tasks, name='mytasks'),
    
    path('<int:wid>/update/<int:tid>/', task_update, name='update'),
    path('<int:wid>/delete/<int:tid>/', task_delete, name='delete'),
    path('<int:wid>/complete/<int:tid>/', task_complete, name='complete'),
    
    path('all-tasks-of-mine/', atom, name='atom'),
]

workspaces/urls.py
from django.urls import path
from .views import *


app_name = 'workspaces'
urlpatterns = [
    path('all/', all_workspace_list, name='all'),
    path('joined/', joined_workspace_list, name='joined'),
    path('own/', own_workspace_list, name='own'),
    
    path('<int:id>/details/', Workspace_details, name='details'),
    path('<int:id>/update/', Workspace_update, name='update'),
    path('<int:id>/delete/', Workspace_delete, name='delete'),        
]

workspaces/models.py
from django.contrib.auth.models import User
from django.db import models


CATEGORY_CHOICES = [
    ('EDU', 'Education'),
    ('IT', 'Engineering-IT'),
    ('MRK', 'Marketing'),	
    ('OPR', 'Operations'),
    ('SMB', 'Small Business'),
    ('HRS', 'Human Resources'),
    ('CRM', 'Sales CRM'),
    ('SCL', 'School'),
    ('HSW', 'Housework'),
    ('PRS', 'Personal Stuff'),
]

class Category(models.Model): 
    title = models.CharField(max_length=50, choices=CATEGORY_CHOICES, unique=True)
    
    def __str__(self) -> str:
        return self.get_title_display() # show full title django-built-in method
    
class Tag(models.Model):
    title = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.title
    

class Workspace(models.Model): 
    # MAIN..............................
    name        = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    
    # PERMISSIONS.......................
    host                   = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wh') # WHO Created Workspace with host permissions
    add_task_permission    = models.ManyToManyField(User, blank=True, related_name='watp')
    edit_ws_permission = models.ManyToManyField(User, blank=True, related_name='wutp')
    
    # EXTRA..............................
    member_count = models.IntegerField(default=1)
    public       = models.BooleanField(default=False)
    
    # RELATIONS.........................
    category   = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag        = models.ManyToManyField(Tag, related_name='workspace')
    members    = models.ManyToManyField(User, related_name='workspace')
    
    def __str__(self) -> str:
        return f"{self.name} -> count: {self.member_count} | members: {self.members}" 

workspaces/forms.py
from django import forms
from .models import Workspace


class AddNewWorkspaceForm(forms.ModelForm):

    class Meta:
        model = Workspace
        fields = [
            'name',
            'description',
            'category',
            'tag',
            'public',
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control',
            'id': 'name',
            'name': 'name',
            'placeholder': 'Name...',
            'required': '',
        })
        self.fields['description'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control',
            'id': 'description',
            'name': 'description',
            'placeholder': 'Workspace about...',
            'required': '',
        })
        self.fields['category'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control',
            'id': 'category',
            'name': 'category',
        })
        self.fields['tag'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['public'].widget.attrs.update({
            'class': 'block me-auto'
        })

class UpdateWorkspaceForm(forms.ModelForm):

    class Meta:
        model = Workspace
        fields = [
            'name',
            'description',
            'category',
            'tag',
            'public',
            'add_task_permission',
            'edit_ws_permission',
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control',
            'id': 'name',
            'name': 'name',
            'placeholder': 'Name...',
            'required': '',
        })
        self.fields['description'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control',
            'id': 'description',
            'name': 'description',
            'placeholder': 'Workspace about...',
            'required': '',
        })
        self.fields['category'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control disabled',
            'id': 'category',
            'name': 'category',
        })
        self.fields['tag'].widget.attrs.update({
            'class': 'form-control disabled',
        })
        self.fields['public'].widget.attrs.update({
            'class': 'block me-auto'
        })
        self.fields['add_task_permission'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control text-primary',
            'id': 'add_task_permission',
            'name': 'add_task_permission',
        })
        self.fields['edit_ws_permission'].widget.attrs.update({
            'type': 'text',
            'class': 'form-control text-danger',
            'id': 'edit_ws_permission',
            'name': 'edit_ws_permission',
        })
    
class JoinMemberForm(forms.ModelForm):

    class Meta:
        model = Workspace
        fields = ['members', 'member_count']
    

workspaces/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q, F
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import *
from .models import *


"""\__________________________WORKSPACE__________________________/"""

"""\______________________ALL______________________/"""
def all_workspace_list(request):
    searched = request.GET.get('searched')
    if searched:
        searched.strip()

    style = {
        'pb': 'pb-4',
        'mb': 'mb-4',
    }
    if searched:
        searched_workspaces = Workspace.objects.select_related('category').filter(
            Q(public=True), 
            Q(name__icontains=searched) | 
            Q(tag__title__icontains=searched) | 
            Q(category__title__icontains=searched)
        ).distinct().order_by('-member_count')
        context = {
            'style': style,
            'pws': searched_workspaces
        }
    
    else:    
        all_public_workspaces = Workspace.objects.prefetch_related('members').filter(public=True).order_by('-member_count')
        context = {
            'style': style,
            'pws': all_public_workspaces,
        }
    
    template = 'workspace_list.html'
    return render(request, template, context=context)

"""\______________________JOINED______________________/"""
@login_required
def joined_workspace_list(request):
    searched = request.GET.get('searched')
    if searched:
        searched.strip()
    
    style = {
        'pb': 'pb-4',
        'mb': 'mb-4',
    }
    if searched:
        searched_workspaces = Workspace.objects.select_related('category').filter(
            Q(public=True), 
            Q(name__icontains=searched) | 
            Q(tag__title__icontains=searched) | 
            Q(category__title__icontains=searched)
        ).distinct().order_by('-member_count')
        context = {
            'style': style,
            'pws': searched_workspaces
        }
    
    else:
        joined_workspaces = Workspace.objects.prefetch_related('members').all().order_by('-member_count')
        
        context = {
            'style': style,
            'pws': joined_workspaces,
        }
        
    template = 'workspace_list.html'
    return render(request, template, context=context)

"""\______________________OWN______________________/"""
@login_required
def own_workspace_list(request):
    searched = request.GET.get('searched')
    if searched:
        searched.strip()
    
    style = {
        'pb': 'pb-4',
        'mb': 'mb-4',
    }
    if searched:
        searched_workspaces = Workspace.objects.select_related('category').filter(
            Q(public=True), 
            Q(name__icontains=searched) | 
            Q(tag__title__icontains=searched) | 
            Q(category__title__icontains=searched)
        ).distinct().order_by('-member_count')
        context = {
            'style': style,
            'pws': searched_workspaces
        }

    if request.method == "POST":
        form = AddNewWorkspaceForm(request.POST or None)
        if form.is_valid():
            form_data = form.save(commit=False)
            form_data.host = request.user
            
            form.save()
            messages.success(
                request, 
                f'your Workspace created Successfully! :D'
            )
            return redirect(reverse('workspaces:own'))
    
    style = {
        'bottom': 'border-bottom-0',
    }
    own_workspaces = Workspace.objects.select_related('category').filter(host=request.user).order_by('-member_count')
    form = AddNewWorkspaceForm() # Add new ws Form
    context = {
        'style': style,
        'pws': own_workspaces,
        'form': form,
    }
    template = 'workspace_list.html'
    return render(request, template, context=context)

@login_required
def Workspace_details(request, id):
    workspace_detail = Workspace.objects.get(id=id)
    tags             = Tag.objects.prefetch_related('workspace').filter(workspace__id=id)

    if request.method == 'POST': # BUG FIX THIS...<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        form = JoinMemberForm()
        form.members = request.user
        
        number_of_members = Workspace.objects.get(id=id).member_count
        print(number_of_members)
        form.member_count = number_of_members + 1
        
        form.save()
        
        messages.success(
            request, 
            f'Welcome to {workspace_detail.name} '
        )
        return redirect(reverse('tasks:all', args=[id]))
        
    context = {
        'footer': True,
        'WsId': id,
        'tags': tags,
        'wsd': workspace_detail,
    }
    
    template = 'workspace_details.html'
    return render(request, template, context=context)
    
@login_required
def Workspace_update(request, id):
    workspace = Workspace.objects.get(id=id)
    form = UpdateWorkspaceForm(instance=workspace)
    if request.method == "POST":
        form = UpdateWorkspaceForm(request.POST, instance=workspace)
        print('================', request.POST)
        if form.is_valid():
            form.save()
            
            messages.success(
                request, 
                f'your Workspace update Successfully! :D'
            )
            return redirect(reverse('workspaces:own'))
    
    context = {
        'form': form,
        'ws': workspace
    }
    template = 'update_workspace.html'
    return render(request, template, context=context)

@login_required
def Workspace_delete(request, id):
    workspace = Workspace.objects.get(
        Q(id=id) & 
        Q(host=request.user) | 
        Q(edit_ws_permission=request.user)
    )
    if workspace:
        workspace.delete()
        messages.success(
            request, 
            f'Your workspace has been Successfully deleted!'
        )
    else:
        messages.error(
            request, 
            f'Sorry! This workspace has Not been deleted! :D'
        )
        
    return redirect(reverse('workspaces:own'))
    

workspaces/templates/update_workspace.html
{% extends "base.html" %}
{% load static %}

{% block title %} UPDATE-WORKSPACE {% endblock %}

{% block body %}
<div class="position-absolute text-white mt-5">
  <h1 class="text-center">Update Workspace</h1>
  <h2 class="text-center"><" {{ ws.name }} "></h2>
  <form method=POST> {% csrf_token %}
    <div class="mx-5">
      <label class="form-label mt-3" for="name">Workspace Name</label>
        {{ form.name }}

        <label class="form-label mt-3" for="description">Description</label>
        {{ form.description }}

        <label class="form-label mt-3" for="public">tag</label>
        {{ form.tag }}
        
        <label class="form-label mt-3" for="public">category</label>
        {{ form.category }}

        <label class="form-label mt-3" for="public">Public?</label>
        {{ form.public }}
      
        <label class="d-block form-label mt-3 text-primary" for="add_task_permission">Add Task Permission</label>
        {{ form.add_task_permission }}
        
        <label class="d-block form-label mt-3 text-danger" for="edit_ws_permission">Edit Permission</label>
        {{ form.edit_ws_permission }}

      <br class="my-3">
      <div class="text-start h3 mb-0">
        <button 
          class="py-2 px-3 btn-lg btn-warning badge text-bg-warning rounded-pill" 
          type="submit"> Update
        </button>
   
      </div>
    </div>
  </form>
      <a class="text-start h3" href="{% url "workspaces:own" %}">          
        <button 
          class="ms-5 mt-0 py-2 px-3 btn-lg btn-warning badge text-bg-danger rounded-pill" 
          type="exit"> Back...
        </button>
      </a>       
</div>
{% endblock %}

workspaces/templates/workspace_details.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ wsd.name }} {% endblock %}

{% block body %}
  <!-- HEADER INFO -->
  <header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
        <h1 class="display-4 fw-bold text-warning"> {{ wsd.name }} </h1>
        <p class="lead fw-normal text-white-50 mb-0">
          Made by [ <span class="text-warning">{{ wsd.host }}</span> ]
        </p>
      </div>
    </div>
  </header>

  <!-- BODY -->
  <section class="container-fluid py-5 text-white">
      <div class="container-lg">
          
          <section class="py-5">
              <div class="container">
                <div class="row gx-5">

                  <!-- IMAGE -->
                  <aside class="col-lg-6">
                    <div class="border rounded-4 mb-3 d-flex justify-content-center" style="background-color: #dee1e6;">
                        <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{% static '002.png' %}" />
                    </div>
                  </aside>

                  <main class="col-lg-6">
                    <div class="ps-lg-3">

                      <!-- TITLE -->
                      <h3 class="title text-white fw-custom"> {{ wsd.name }}</h3>
                      <div class="d-flex flex-row my-3">

                        <span class="text-muted fw-custom"><i class="fas fa-shopping-basket fa-sm mx-1"></i>------------</span>
                      </div>
                      
                      <!-- DESCRIPTION -->
                      <p class="fw-custom">
                        {{ wsd.description }}
                      </p>
                      
                      <!-- MORE INFO -->
                      <div class="row mb-5">
                        <dt class="col-3 fw-custom">Host:</dt>
                        <dd class="col-9 fw-custom text-white">{{ wsd.host }}</dd>

                        <dt class="col-3 fw-custom">Members:</dt>
                        <dd class="col-9 fw-custom text-white">{{ wsd.member_count }}</dd>
            
                        <dt class="col-3 fw-custom">Category:</dt>
                        <dd class="col-9 fw-custom text-white">{{ wsd.category }}</dd>
            
                        <dt class="col-3 fw-custom">Tags:</dt> {% for tag in tags %}
                        <dd class="col-2 text-white">{{ tag }},</dd>
                        {% endfor %}
                      </div>
            
                      <hr />
                      
                      <!-- BUTTONS -->
                      {% if wsd.public %} 
                      <form method=POST class=" d-inline "> {% csrf_token %}
                        <button class="btn-sm rounded-5 border-0" style="background-color: rgb(22, 74, 65);">
                          <a class="btn btn-success my-1 fw-bold">
                            <i class="bi bi-bag text-center">Join</i>
                          </a>
                        </button>
                      </form>
                      {% else %}
                        <a href="#" class="btn btn-secondary my-1"><i class="bi bi-bag text-center"> Request </i></a>
                      {% endif %}
                      {% if user.request == wsd.host or user.request in wsd.edit_ws_permission.all %}
                        <a href="{% url "workspaces:update" WsId %}" class="btn btn-info my-1"> <i class="bi bi-save2"></i> Update </a>
                        <a href="{% url "workspaces:delete" WsId %}" class="btn btn-danger my-1"> <i class="bi bi-save2"></i> Delete </a>
                      {% endif %}
                      <a href="{% url "workspaces:all" %}" class="btn btn-info my-1"> <i class="bi bi-cart3"></i> Back </a>


                    </div>
                  </main>

                </div>
              </div>
          </section>

      </div>
  </section>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

workspaces/templates/workspace_list.html
{% extends "base.html" %}
{% load static %}

{% block header_setting %}
  <link rel="stylesheet" href="{% static 'search_bar.css' %}">
  <link rel="stylesheet" href="{% static 'modal.css' %}">
{% endblock %}
{% block title %} WORKSPACE {% endblock %}

{% block body %}
<div class="container px-4 px-lg-5 mt-0">
  {% comment %} SEARCH & FILTER BAR {% endcomment %}
  <div class="text-center shadow-lg rounded-top-3 border border-warning {{ style.mb }} {{ style.pb }} {{ style.bottom }} mb-0 d-flex flex-wrap align-items-center justify-content-center gap-2" style="background-color: rgb(22, 74, 65);">
    
    {% comment %} SEARCH BAR {% endcomment %}
    <form class="mb-3 pt-5" action="{% url 'workspaces:all' %}" role="search">
      <div class="sb-animate">
        <input  name="searched" type="search" class="form-control-dark" placeholder="Search Here..." aria-label="Search">
        <div class="search"></div>
      </div>
    </form>
    
    {% comment %} FILTER BAR {% endcomment %}
    <div class="row mt-3 d-wrap d-flex">
      <a class="text-decoration-none text-dark col-4 text-center" href="{% url "workspaces:all" %}">
        <button class="p-3 btn-lg btn-warning mx-4 badge text-bg-warning rounded-pill" type="button">All Workspaces</button>
      </a>
      <a class="text-decoration-none text-dark col-4 text-center" href="{% url "workspaces:own" %}">
        <button class="p-3 btn-lg btn-warning mx-4 badge text-bg-warning rounded-pill" type="button">My Workspaces</button>
      </a>
      <a class="text-decoration-none text-dark col-4 text-center" href="{% url "workspaces:joined" %}">
        <button class="p-3 btn-lg btn-warning mx-4 badge text-bg-warning rounded-pill" type="button">Joined Workspaces</button>
      </a>
    </div>
  </div>

  {% comment %} add-update-delete OPTIONS {% endcomment %}
  {% if request.path == "/workspace/own/" %}
  <ul class="dropdown-menu d-block rounded-top-0 position-static mb-4 mx-0 border-warning border-top-0 w-220px" data-bs-theme="dark" style="background-color: rgb(22, 74, 65);">
    <li><hr class="dropdown-divider"></li>
    <li>
      <a id="myButton" class="dropdown-item d-flex gap-2 align-items-center justify-content-center">
        <img src="{% static "add.png" %}" width="30" height="30"/>
        Add New
        <img src="{% static "add.png" %}" width="30" height="30"/>
      </a>
    </li>
  </ul>
  {% comment %} add-update-delete MODAL {% endcomment %}
  <div id="myModal" class="modal align-content-center justify-content-center">
    <div class="modal-content bg-dark">
      <div class="text-white">
        <h1>Add New Workspace</h1>
        <form method=POST> {% csrf_token %}
          <label class="form-label mt-3" for="name">Workspace Name</label>
            {{ form.name }}

            <label class="form-label mt-3" for="description">Description</label>
            {{ form.description }}
            
            <label class="form-label mt-3" for="category">Category</label>
            {{ form.category }}
            
            <label class="form-label mt-3" for="tag">Tags</label>
            {{ form.tag }}
            
            <label class="form-label mt-3" for="public">Public?</label>
            {{ form.public }}
          
          <br class="my-3">
          <div class="text-start h3">
            <button 
              class="py-2 px-3 btn-lg btn-warning badge text-bg-warning rounded-pill" 
              type="submit"> Add
            </button>
            <span class="close">
              <button 
                class="py-2 px-3 btn-lg btn-warning badge text-bg-danger rounded-pill" 
                type="exit"> Cancel
              </button>
            </span>
            {% comment %} <input class="bg-warning" type='submit' value='save'/> {% endcomment %}
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}
  {% comment %} WORKSPACE CARD'S {% endcomment %}
  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    {% for workspace in pws %}
    {% comment %} Joined Page {% endcomment %}
    {% if request.path == "/workspace/joined/" and request.user in workspace.members.all %}
    <div class="col mb-5">
      <div class="card h-100 shadow-lg text-white" style="background-color: rgb(22, 74, 65);">
        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ workspace.category }}</div>
          <img class="card-img-top" src="{% static "001.png" %}" alt="workspace_pic">
          <div class="card-body p-4">
            <div class="text-center">
              <h3 class="fw-bolder text-warning">{{ workspace.name }}</h3>

              <span class="text-white d-block fw-custom">
                Host: [ <span class="text-warning">{{ workspace.host }}</span> ]
              </span>
              <span class="text-white d-block fw-custom">
                Members: [ <span class="text-warning">{{ workspace.member_count }}</span> ]
              </span>
              <br class="mb-2">

              <span class="text-white fw-custom">{{ workspace.description|truncatechars:80 }}</span>
            </div>
          </div>
          <div class="card-footer mb-2 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-warning mt-auto fw-custom px-5" href="{% url "tasks:all" workspace.id %}">
                <img src="{% static "add.png" %}" width="30" height="30"/>
                OPEN
                <img src="{% static "add.png" %}" width="30" height="30"/>  
              </a>
            </div>
          </div>
    {% comment %} Own Page  {% endcomment %}
    {% elif request.path == "/workspace/own/" and workspace.host == request.user %}
    <div class="col mb-5">
      <div class="card h-100 shadow-lg text-white" style="background-color: rgb(22, 74, 65);">
        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ workspace.category }}</div>
          <img class="card-img-top" src="{% static "001.png" %}" alt="workspace_pic">
          <div class="card-body p-4">
            <div class="text-center">
              <h3 class="fw-bolder text-warning">{{ workspace.name }}</h3>

              <span class="text-white d-block fw-custom">
                Host: [ <span class="text-warning">{{ workspace.host }}</span> ]
              </span>
              <span class="text-white d-block fw-custom">
                Members: [ <span class="text-warning">{{ workspace.member_count }}</span> ]
              </span>
              <br class="mb-2">

              <span class="text-white fw-custom">{{ workspace.description|truncatechars:80 }}</span>
            </div>
          </div>
          <div class="d-block rounded-top-0 position-static mb-2 mx-0 w-220px" data-bs-theme="dark" style="background-color: rgb(22, 74, 65);">
            <div class="card-footer border-top-0 bg-transparent">
              <div class="row text-center mx-4">
                <a class="col btn btn-outline-warning rounded-end-0" href="{% url "workspaces:update" workspace.id %}">
                  <img src="{% static "update.png" %}" width="30" height="30"/>
                  Update
                </a>
                <button onclick="callAlert(this)" class="col btn btn-outline-danger rounded-start-0" link="{% url "workspaces:delete" workspace.id %}">
                  Delete
                  <img src="{% static "delete.png" %}" width="30" height="30"/>
                </button>
              </div>
            </div>
            <div class="d-block card-footer border-top-0 bg-transparent">
              <div class="text-center">
                <a class="btn btn-outline-warning mt-auto fw-custom px-5" href="{% url "tasks:all" workspace.id %}">
                  <img src="{% static "add.png" %}" width="30" height="30"/>
                  OPEN
                  <img src="{% static "add.png" %}" width="30" height="30"/>  
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% comment %} All Page  {% endcomment %}
    {% elif request.path == "/workspace/all/" %}
    <div class="col mb-5">
      <div class="card h-100 shadow-lg text-white" style="background-color: rgb(22, 74, 65);">
        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ workspace.category }}</div>
          <img class="card-img-top" src="{% static "001.png" %}" alt="workspace_pic">
          <div class="card-body p-4">
            <div class="text-center">
              <h3 class="fw-bolder text-warning">{{ workspace.name }}</h3>

              <span class="text-white d-block fw-custom">
                Host: [ <span class="text-warning">{{ workspace.host }}</span> ]
              </span>
              <span class="text-white d-block fw-custom">
                Members: [ <span class="text-warning">{{ workspace.member_count }}</span> ]
              </span>
              <br class="mb-2">

              <span class="text-white fw-custom">{{ workspace.description|truncatechars:80 }}</span>
            </div>
          </div>
          
          {% if workspace.host == request.user %}
          <div class="d-block rounded-top-0 position-static mb-2 mx-0 w-220px" data-bs-theme="dark" style="background-color: rgb(22, 74, 65);">
            <div class="card-footer border-top-0 bg-transparent">
              <div class="row text-center mx-4">
                <a class="col btn btn-outline-warning rounded-end-0" href="{% url "workspaces:update" workspace.id %}">
                  <img src="{% static "update.png" %}" width="30" height="30"/>
                  Update
                </a>
                <button onclick="callAlert(this)" class="col btn btn-outline-danger rounded-start-0" link="{% url "workspaces:delete" workspace.id %}">
                  Delete
                  <img src="{% static "delete.png" %}" width="30" height="30"/>
                </button>
              </div>
            </div>
            <div class="d-block card-footer border-top-0 bg-transparent">
              <div class="text-center">
                <a class="btn btn-outline-warning mt-auto fw-custom px-5" href="{% url "tasks:all" workspace.id %}">
                  <img src="{% static "add.png" %}" width="30" height="30"/>
                  OPEN
                  <img src="{% static "add.png" %}" width="30" height="30"/>  
                </a>
              </div>
            </div>
          </div>
          {% elif request.user in workspace.members.all %}
          <div class="card-footer mb-2 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-warning mt-auto fw-custom px-5" href="{% url "tasks:all" workspace.id %}">
                <img src="{% static "add.png" %}" width="30" height="30"/>
                OPEN
                <img src="{% static "add.png" %}" width="30" height="30"/>  
              </a>
            </div>
          </div>
          {% else %}
          <div class="card-footer mb-2 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-outline-warning mt-auto fw-custom px-5" href="{% url "workspaces:details" workspace.id %}">
                <img src="{% static "visit.png" %}" width="30" height="30"/>
                VISIT
                <img src="{% static "visit.png" %}" width="30" height="30"/>
              </a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
  <script>
  var myButton = document.getElementById("myButton");
  var myModal = document.getElementById("myModal");
  var closeButton = document.getElementsByClassName("close")[0];

  function openModal() {
    myModal.style.display = "block";
  }

  function closeModal() {
    myModal.style.display = "none";
  }

  myButton.addEventListener("click", openModal);
  closeButton.addEventListener("click", closeModal);

  function callAlert(element) {
    var userResponse = confirm("Are You Sure?");
    var link = element.getAttribute("link");

    if (userResponse) {
        window.location.href = link;
    } else {

    }
  }
</script>
{% comment %} <script>
  const basicAutocomplete = document.querySelector('search-autocomplete');
  const data = ['One', 'Two', 'Three', 'Four', 'Five'];
  const dataFilter = (value) => {
    return data.filter((item) => {
      return item.toLowerCase().startsWith(value.toLowerCase());
    });
  };

  new mdb.Autocomplete(basicAutocomplete, {
    filter: dataFilter
  });
</script> {% endcomment %}
{% endblock %}