conf/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from .views import * # for Home view & template


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home, name='home'),
    path('sad/', sad, name='sad'),
    
    path('accounts/', include('users.urls')),        #USERS
    path('workspace/', include('workspaces.urls')),  #WORKSPACE
    path('workspace/id/', include('tasks.urls')),    #TASKS
    
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import *


app_name = 'tasks'
urlpatterns = [
    path('<int:id>/all/', all_tasks, name='all'),
    path('<int:id>/done/', done_tasks, name='done'),
    path('<int:id>/pending/', pending_tasks, name='pending'),
    path('<int:id>/mytasks/', own_tasks, name='mytasks'),
    
    path('<int:wid>/update/<int:tid>/', task_update, name='update'),
    path('<int:wid>/delete/<int:tid>/', task_delete, name='delete'),
    path('<int:wid>/complete/<int:tid>/', task_complete, name='complete'),
    
    path('all-tasks-of-mine/', atom, name='atom'),
]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views # for login, logout, &... views


app_name = 'users'
urlpatterns = [
    # path('', signup, name='signup'),
    path('signup/', signup, name='signup'),
    # path(
    #     'login/', 
    #     auth_views.LoginView.as_view(
    #             template_name='login.html'
    #         ), 
    #     name='login'
    # ),
    path('login/', login_view, name='login'),
    path(
        'logout/', 
        auth_views.LogoutView.as_view(), 
        name='logout'
    ),
]

workspaces/urls.py
from django.urls import path
from .views import *


app_name = 'workspaces'
urlpatterns = [
    path('all/', all_workspace_list, name='all'),
    path('joined/', joined_workspace_list, name='joined'),
    path('own/', own_workspace_list, name='own'),
    
    path('<int:id>/details/', Workspace_details, name='details'),
    path('<int:id>/update/', Workspace_update, name='update'),
    path('<int:id>/delete/', Workspace_delete, name='delete'),        
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="bootstrap/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-icons.css' %}">

  {% block header_setting %}{% endblock %}
  <title>{% block title %}TMS{% endblock %}</title>
</head>
<!-- content-card for cards -->

<!-- change background color in other templates -->
<body style="background-color: rgb(22, 74, 65);">
  <!-- my web navigation -->
  
  <header>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} mb-1 py-2">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <nav class="p-1 text-white" style="background-color: rgb(22, 74, 65);">
      <div class="mx-5">
        <div class="d-flex flex-wrap align-items-center">
          <a href="/" class="d-flex me-4 align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img class="bi me-2" src="{% static 'tms-logo.png' %}" width="75" height="70" aria-label="Bootstrap"/>
            <h3>Thornless</h3>
          </a>
  
          <ul class="nav col-lg-auto ms-lg-auto me-3">
            <li><a href="/" class="nav-link px-2 text-warning">HOME</a></li>
            <li><a href="/workspace/all/" class="nav-link px-2 text-white">Workspaces</a></li>
            <li><a href="{% url "tasks:atom" %}" class="nav-link px-2 text-white">MyTasks</a></li>
            <li>
              <!-- <a href="/about" class="nav-link px-2 text-white">Invite</a> -->
              <button type="button" class="btn text-white position-relative">
                Invite <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">+99 <span class="visually-hidden">unread messages</span></span>
              </button>
            </li>
          </ul>
          
          <div class="text-end">
            {% if user.is_authenticated %}
            <div class="dropdown text-end">
              <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static "004.png" %}" alt="mdo" width="32" height="32" class="rounded-circle">
              </a>
              <ul class="dropdown-menu text-small bg-info">
                <li><b class="dropdown-item text-center fw-bold pt-0">< {{ request.user }} ></b></li>
                <li><hr class="dropdown-divider mt-0"></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url "users:logout" %}">Logout</a></li>
              </ul>
            </div>
            {% else %}
            <a href="{% url "users:login" %}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
            <a href="{% url "users:signup" %}"><button type="button" class="btn btn-warning">Sign-up</button></a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% block nav %}{% endblock %}
  </header>
  
  
  <main>
    <div id="body">{% block body %}{% endblock %}</div>
  </main>
  {% if footer %}
  <div class="position-absolute container top-100 start-50 translate-middle">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-2 my-4 border-top">
      <p class="col-md-4 mb-0 text-white">© 2023 | Dev by PKPY</p>
  
      <div class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto">
        <img class="bi me-2" src="{% static 'tms-logo.png' %}" width="55" height="50" aria-label="Bootstrap"/>
      </div>
  
      <ul class="nav col-lg-auto ms-lg-auto me-3">
        <li><a href="/" class="nav-link px-2 text-white">home</a></li>
        <li><a href="{% url "workspaces:all" %}" class="nav-link px-2 text-white">workspaces</a></li>
        <li><a href="{% url "tasks:atom" %}" class="nav-link px-2 text-white">myTasks</a></li>
        </li>
      </ul>
    </footer>
  </div>
  {% endif %}
  <script src="{% static 'bootstrap.bundle.min.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} HOME {% endblock %}

{% block body %}
  <div class="pb-5 container">
    <div>
      <h1 class="position-absolute end-0 bottom-1 fw-bolder fw-italic" style="font-size: 500px; color: rgb(253, 220, 228);"> 
        TASK 
      </h1>
    </div>
    <img class="position-absolute end-0" src="{% static '006.png' %}" style="width: 50%;">

    <div class="position-absolute bottom-0 start-0 mx-5 text-white" style="font-size: 30px;">
      <b class="text-warning" style="font-size: 50px;"> - WELCOME TO THORNLESS - </b>
      <p> 
        Thornless is a 
        <strong style="color: rgb(239, 3, 108);">task management system</strong> 
        web application.
      </p>
      <p>Tasks is like a cactus with sharp and painful thorns.</p>
      <p>Thornless remove the thorns from this cactus and help you</p>
      <p>
        interact with it more easily. ->
        <span>
          <a href="{% url "workspaces:all" %}"><button type="button" class="btn btn-outline-warning">I NEED THIS :3</button></a>
        </span>
        <span>
          <a href="/sad/"><button type="button" class="btn btn-outline-dark">I DON'T :(</button></a>
        </span>
      </p>
            
    </div>
  </div>
{% endblock %}
<!-- rgb(49, 236, 86) green -->
<!-- rgb(239, 3, 108) red -->
<!-- rgb(238, 114, 248) pink -->

templates/sadcat.html
{% extends "base.html" %}

{% load static %}

{% block title %} SAD:( {% endblock %}

{% block body %}
<div class="container">
  <img class="position-absolute end-0" src="{% static 'sad-cat.gif' %}" alt="Sad-Cat" style="width: 100%;">
  <div class="position-absolute start-50 top-50 translate-middle text-white">
    <h1 style="font-size: 80px;" >you do not like me?</h1>
  </div>
</div>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="bootstrap/bootstrap.bundle.min.js">
  <link rel="stylesheet" href="bootstrap/bootstrap-icons.css">

</head>


 <body>
    <div class="py-5">
      <div class="container">
        <div class="row hidden-md-up">
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
        </div><br>
        <div class="row">
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Card title</h4>
                <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
                <a href="#" class="card-link">link</a>
                <a href="#" class="card-link">Second link</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

</html>